[package]
name = "gps-to-mqtt"
version = "0.1.3"
edition = "2021"

[dependencies]
serialport = "4.6.1"
config = "0.15.5"
paho-mqtt = "0.12.5"
futures = "0.3.31"
lazy_static = "1.5.0"
gumdrop = "0.8.1"
