[package]
name = "gps-to-mqtt"
version = "0.1.2"
edition = "2021"

[dependencies]
serialport = "4.3.0"
config = "0.13.4"
paho-mqtt = "0.12.3"
futures = "0.3.30"
lazy_static = "1.4.0"
gumdrop = "0.8.1"
